# Generated by Django 2.1.4 on 2019-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190111_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
